test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,6 +64,7 @@ jobs:
           push: true
         continue-on-error: true
         id: commit
+      
       - name: retry
         continue-on-error: true
         id: retry1
@@ -79,6 +80,13 @@ jobs:
           echo retry 2nd time
           sleep 30s
           exit 1    
+      - name: try commit again
+        run: |
+          # Retry 3 times before the steps actually fails
+          (echo "===== Maven Deploy Attempt: 1 ====" && commit) || \
+          (echo "===== Maven Deploy Attempt: 2 ====" && commit) || \
+          (echo "===== Maven Deploy Attempt: 3 ====" && commit) || \
+          (echo "==== Maven Deploy Step Failed ====" && exit 1)
       - name: remove changes
         run: git reset -- data.json
       - name: remove data changes
